// src/components/Tree/Tree.jsx
import { forwardRef, useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import { Vector3 } from "three";
import { GhibliShader } from "./GhibliShader";

export const Tree = forwardRef((props, ref) => {
  const { nodes } = useGLTF("/trees.glb");

  const uniforms = useMemo(
    () => ({
      colorMap: {
        value: props.colors,
      },
      brightnessThresholds: {
        value: [0.6, 0.35, 0.001],
      },
      lightPosition: { value: new Vector3(15, 15, 15) },
    }),
    [props.colors],
  );

  console.log(nodes);

  return (
    <group {...props} ref={ref} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Foliage.geometry}
        position={[-0.9, 2, 0.6]}
        scale={[0.6, 0.6, 0.6]}
        rotation={[2, 4, 6]}
      >
        <shaderMaterial
          attach="material"
          {...GhibliShader}
          uniforms={uniforms}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Foliage.geometry}
        position={[1.1, 2, 0.6]}
        scale={[0.6, 0.6, 0.6]}
        rotation={[2, 4, 6]}
      >
        <shaderMaterial
          attach="material"
          {...GhibliShader}
          uniforms={uniforms}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Foliage.geometry}
        position={[-0.8, 2, 0.2]}
        scale={[0.6, 0.6, 0.6]}
        rotation={[2, 4, 6]}
      >
        <shaderMaterial
          attach="material"
          {...GhibliShader}
          uniforms={uniforms}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Foliage.geometry}
        position={[0.2, 2, -1.3]}
        scale={[0.6, 0.6, 0.6]}
        rotation={[2, 4, 6]}
      >
        <shaderMaterial
          attach="material"
          {...GhibliShader}
          uniforms={uniforms}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Foliage.geometry}
        position={[-1, 2, -0.6]}
        scale={[0.6, 0.6, 0.6]}
        rotation={[2, 4, 6]}
      >
        <shaderMaterial
          attach="material"
          {...GhibliShader}
          uniforms={uniforms}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Foliage.geometry}
        position={[1, 2, 0.6]}
        scale={[0.6, 0.6, 0.6]}
        rotation={[2, 4, 6]}
      >
        <shaderMaterial
          attach="material"
          {...GhibliShader}
          uniforms={uniforms}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Foliage.geometry}
        position={[1, 2, 0.2]}
        scale={[0.6, 0.6, 0.6]}
        rotation={[2, 4, 6]}
      >
        <shaderMaterial
          attach="material"
          {...GhibliShader}
          uniforms={uniforms}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Foliage.geometry}
        position={[0, 2.5, 0]}
      >
        <shaderMaterial
          attach="material"
          {...GhibliShader}
          uniforms={uniforms}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Foliage.geometry}
        position={[0, 4.5, 0]}
        scale={[0.6, 0.6, 0.6]}
        rotation={[2, 4, 6]}
      >
        <shaderMaterial
          attach="material"
          {...GhibliShader}
          uniforms={uniforms}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Foliage.geometry}
        position={[0, 5, 0]}
        scale={[0.5, 0.5, 0.5]}
        rotation={[5, 3, 3]}
      >
        <shaderMaterial
          attach="material"
          {...GhibliShader}
          uniforms={uniforms}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Foliage.geometry}
        position={[0, 5, 0]}
        scale={[0.5, 0.5, 0.5]}
        rotation={[2, 4, 8]}
      >
        <shaderMaterial
          attach="material"
          {...GhibliShader}
          uniforms={uniforms}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Foliage.geometry}
        position={[0, 6, 0]}
        scale={[0.4, 0.4, 0.4]}
        rotation={[5, 2, 3]}
      >
        <shaderMaterial
          attach="material"
          {...GhibliShader}
          uniforms={uniforms}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Foliage.geometry}
        position={[0, 6.5, 0]}
        scale={[0.3, 0.3, 0.3]}
        rotation={[4, 6, 4]}
      >
        <shaderMaterial
          attach="material"
          {...GhibliShader}
          uniforms={uniforms}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Foliage.geometry}
        position={[0, 7, 0]}
        scale={[0.3, 0.3, 0.3]}
        rotation={[5, 2, 4]}
      >
        <shaderMaterial
          attach="material"
          {...GhibliShader}
          uniforms={uniforms}
        />
      </mesh>
    </group>
  );
});

useGLTF.preload("/trees.glb");

// src/components/Tree/Tree.svelte
<script lang="ts">
  import { Group, Vector3, type Color } from "three";
  import { T, forwardEventHandlers } from "@threlte/core";
  import { useGltf } from "@threlte/extras";
  import { GhibliShader } from "./GhibliShader";

  export const ref = new Group();
  export let colors: Color[];

  const gltf = useGltf("/trees.glb");

  const component = forwardEventHandlers();

  const instances: {
    position: [number, number, number];
    scale: [number, number, number];
    rotation: [number, number, number];
  }[] = [
    { position: [-0.9, 2, 0.6], scale: [0.6, 0.6, 0.6], rotation: [2, 4, 6] },
    { position: [1.1, 2, 0.6], scale: [0.6, 0.6, 0.6], rotation: [2, 4, 6] },
    { position: [-0.8, 2, 0.2], scale: [0.6, 0.6, 0.6], rotation: [2, 4, 6] },
    { position: [0.2, 2, -1.3], scale: [0.6, 0.6, 0.6], rotation: [2, 4, 6] },
    { position: [-1, 2, -0.6], scale: [0.6, 0.6, 0.6], rotation: [2, 4, 6] },
    { position: [1, 2, 0.6], scale: [0.6, 0.6, 0.6], rotation: [2, 4, 6] },
    { position: [1, 2, 0.2], scale: [0.6, 0.6, 0.6], rotation: [2, 4, 6] },
    { position: [0, 2.5, 0], scale: [1, 1, 1], rotation: [0, 0, 0] },
    { position: [0, 4.5, 0], scale: [0.6, 0.6, 0.6], rotation: [2, 4, 6] },
    { position: [0, 5, 0], scale: [0.5, 0.5, 0.5], rotation: [5, 3, 3] },
    { position: [0, 5, 0], scale: [0.5, 0.5, 0.5], rotation: [2, 4, 8] },
    { position: [0, 6, 0], scale: [0.4, 0.4, 0.4], rotation: [5, 2, 3] },
    { position: [0, 6.5, 0], scale: [0.3, 0.3, 0.3], rotation: [4, 6, 4] },
    { position: [0, 7, 0], scale: [0.3, 0.3, 0.3], rotation: [5, 2, 4] },
  ];

  $: uniforms = {
    colorMap: {
      value: colors,
    },
    brightnessThresholds: {
      value: [0.6, 0.35, 0.001],
    },
    lightPosition: { value: new Vector3(15, 25, 15) },
  };
</script>

{#if $gltf}
  <T is={ref} {...$$restProps} bind:this={$component}>
    <T.Group name="Scene">
      <T.Group rotation={[0, 0, 0]} scale={0.8}>
        {#each instances as { position, scale, rotation }}
          <T.Mesh
            castShadow
            receiveShadow
            geometry={$gltf.nodes.Foliage.geometry}
            {position}
            {scale}
            {rotation}
          >
            <T.ShaderMaterial attach="material" {...GhibliShader} {uniforms} />
          </T.Mesh>
        {/each}
      </T.Group>
    </T.Group>

    <slot {ref} />
  </T>
{/if}
